from __future__ import annotations

ARCHITECTURE_CATALOG = {'procurement': {'title': 'Procurement Workflow',
                 'description': 'Supervisor-led LangGraph orchestration for procurement analysis, reasoning, '
                                'human review, and recommendation generation.',
                 'entry': 'supervisor',
                 'components': {'user_requirement': {'title': 'User Requirement',
                                                     'type': 'Workflow Input',
                                                     'badges': ['User Input', 'Deterministic'],
                                                     'purpose': 'Captures product, quantity, and required '
                                                                'date.',
                                                     'why_needed': 'The workflow requires a complete '
                                                                   'business request before analysis can '
                                                                   'begin.',
                                                     'routing': 'Stored in Agent State and validated before '
                                                                'the Supervisor routes execution.',
                                                     'reads_state': [],
                                                     'reads_database': [],
                                                     'tools': [('Streamlit input controls',
                                                                'Collect product, quantity, and required '
                                                                'date.'),
                                                               ('Input validation',
                                                                'Validate mandatory fields and numeric '
                                                                'values.')],
                                                     'processing': ['Collect request',
                                                                    'Validate request',
                                                                    'Create initial Agent State'],
                                                     'writes_state': ['product_id',
                                                                      'demand_forecast',
                                                                      'required_date',
                                                                      'session_id',
                                                                      'run_id'],
                                                     'returns_to': 'Supervisor Agent',
                                                     'next_routes': ['Demand & Inventory Analyst',
                                                                     'Validation failure'],
                                                     'source': 'streamlit_app.py / workflow entry',
                                                     'example': {'product_id': 'BHU-6205',
                                                                 'demand_forecast': 80,
                                                                 'required_date': '2026-07-26'}},
                                'agent_state': {'title': 'Agent State',
                                                'type': 'Shared Workflow Memory',
                                                'badges': ['Stateful', 'Shared', 'LangGraph'],
                                                'purpose': 'Carries inputs and node outputs across the '
                                                           'workflow.',
                                                'why_needed': 'Every node reads prior results and returns '
                                                              'explicit updates without hidden global state.',
                                                'routing': 'The Supervisor reads Agent State before each '
                                                           'routing decision.',
                                                'reads_state': ['All current workflow fields'],
                                                'reads_database': [],
                                                'tools': [('AgentState schema',
                                                           'Defines the state contract.'),
                                                          ('LangGraph state merging',
                                                           'Combines node updates into the shared state.')],
                                                'processing': ['Store inputs',
                                                               'Store node outputs',
                                                               'Expose routing flags'],
                                                'writes_state': ['demand_analysis',
                                                                 'supplier_intelligence_output',
                                                                 'risk_complexity_plan',
                                                                 'contracted_reasoning',
                                                                 'spot_reasoning',
                                                                 'decision_aggregation'],
                                                'returns_to': 'Supervisor Agent',
                                                'next_routes': ['Any node selected by the Supervisor'],
                                                'source': 'agents/agent_state.py',
                                                'example': {'selected_route': 'contracted_then_spot',
                                                            'recommended_strategy': 'spot_procurement'}},
                                'supervisor': {'title': 'Supervisor Agent',
                                               'type': 'LangGraph Orchestrator',
                                               'badges': ['Main Controller',
                                                          'Conditional Routing',
                                                          'Parallel'],
                                               'purpose': 'Owns orchestration, validation, routing, parallel '
                                                          'execution, failure handling, and final result '
                                                          'assembly.',
                                               'why_needed': 'The workflow is conditional; not every request '
                                                             'needs all nodes or both reasoning branches.',
                                               'routing': 'Central controller that delegates work, receives '
                                                          'state updates, and decides the next step.',
                                               'reads_state': ['product_id',
                                                               'demand_forecast',
                                                               'required_date',
                                                               'demand_analysis',
                                                               'supplier_intelligence_output',
                                                               'risk_complexity_plan',
                                                               'contracted_reasoning',
                                                               'spot_reasoning',
                                                               'decision_aggregation'],
                                               'reads_database': ['None directly; database work is delegated '
                                                                  'to specialized nodes and tools.'],
                                               'tools': [('LangGraph StateGraph',
                                                          'Defines nodes, edges, and conditional routes.'),
                                                         ('Conditional routers',
                                                          'Select the next node from Agent State.'),
                                                         ('Parallel executor',
                                                          'Runs contracted and spot branches concurrently.'),
                                                         ('Workflow exception handling',
                                                          'Converts failures into controlled workflow '
                                                          'errors.')],
                                               'processing': ['Validate input',
                                                              'Route nodes',
                                                              'Coordinate parallel branches',
                                                              'Return final recommendation'],
                                               'writes_state': ['routing flags',
                                                                'execution mode',
                                                                'workflow status',
                                                                'final state'],
                                               'returns_to': 'Application UI',
                                               'next_routes': ['Demand Analyst',
                                                               'Supplier Intelligence',
                                                               'Risk Planner',
                                                               'Parallel Executor',
                                                               'Aggregator',
                                                               'Complete',
                                                               'Failure'],
                                               'source': 'agents/supervisor.py',
                                               'example': {'selected_route': 'contracted_then_spot',
                                                           'execution_mode': 'parallel'}},
                                'demand_analyst': {'title': 'Demand & Inventory Analyst',
                                                   'type': 'Deterministic Agent',
                                                   'badges': ['Deterministic', 'Database Tools', 'No LLM'],
                                                   'purpose': 'Determines which BOM items need procurement '
                                                              'after inventory, reservations, open POs, and '
                                                              'safety stock.',
                                                   'why_needed': 'Supplier analysis should run only for '
                                                                 'actual procurement shortfalls.',
                                                   'routing': 'The Supervisor routes here first to decide '
                                                              'whether procurement is required.',
                                                   'reads_state': ['product_id',
                                                                   'demand_forecast',
                                                                   'required_date'],
                                                   'reads_database': ['Products',
                                                                      'BOM',
                                                                      'Inventory',
                                                                      'Reservations',
                                                                      'Open POs',
                                                                      'Safety stock',
                                                                      'Lead times'],
                                                   'tools': [('BOM lookup',
                                                              'Retrieve component requirements.'),
                                                             ('Inventory lookup',
                                                              'Read stock, reservations, and safety stock.'),
                                                             ('Open PO lookup',
                                                              'Read quantities already on order.'),
                                                             ('Net requirement calculator',
                                                              'Compute remaining procurement quantity.')],
                                                   'processing': ['Expand BOM demand',
                                                                  'Calculate available inventory',
                                                                  'Subtract open POs',
                                                                  'Add safety stock',
                                                                  'Return positive shortages'],
                                                   'writes_state': ['demand_analysis',
                                                                    'items_requiring_procurement'],
                                                   'returns_to': 'Supervisor Agent',
                                                   'next_routes': ['Supplier Intelligence',
                                                                   'Workflow Complete'],
                                                   'source': 'agents/demand_inventory_analyst.py',
                                                   'example': {'item_id': 'BR-6205',
                                                               'gross_requirement': 330,
                                                               'net_requirement': 320}},
                                'supplier_intelligence': {'title': 'Supplier Intelligence Agent',
                                                          'type': 'Deterministic Enrichment Agent',
                                                          'badges': ['Deterministic',
                                                                     'Commercial Data',
                                                                     'No LLM'],
                                                          'purpose': 'Builds normalized contracted and spot '
                                                                     'supplier facts for each required item.',
                                                          'why_needed': 'Reasoning should consume validated '
                                                                        'facts instead of raw tables.',
                                                          'routing': 'The Supervisor routes here only when '
                                                                     'demand analysis finds shortages.',
                                                          'reads_state': ['demand_analysis',
                                                                          'items_requiring_procurement',
                                                                          'required_date'],
                                                          'reads_database': ['Supplier mappings',
                                                                             'Contracted and spot pricing',
                                                                             'MOQ',
                                                                             'Capacity',
                                                                             'Lead times',
                                                                             'Quality',
                                                                             'On-time delivery',
                                                                             'Risk',
                                                                             'Discount thresholds'],
                                                          'tools': [('get_supplier_options()',
                                                                     'Return eligible suppliers.'),
                                                                    ('get_supplier_details()',
                                                                     'Load performance and risk.'),
                                                                    ('Contracted cost calculator',
                                                                     'Apply MOQ and valid discounts.'),
                                                                    ('Spot cost calculator',
                                                                     'Compute spot cost without contracted '
                                                                     'discounts.'),
                                                                    ('Capacity validation',
                                                                     'Verify supplier fulfillment '
                                                                     'capacity.')],
                                                          'processing': ['Load suppliers',
                                                                         'Calculate MOQ and overage',
                                                                         'Calculate costs',
                                                                         'Evaluate discounts',
                                                                         'Attach performance and risk'],
                                                          'writes_state': ['supplier_intelligence_output'],
                                                          'returns_to': 'Supervisor Agent',
                                                          'next_routes': ['Risk & Complexity Planner',
                                                                          'Manual review / failure'],
                                                          'source': 'agents/supplier_intelligence_agent.py / '
                                                                    'agent_tools.py',
                                                          'example': {'item_id': 'BR-6205',
                                                                      'supplier_count': 5}},
                                'risk_planner': {'title': 'Risk & Complexity Planner',
                                                 'type': 'Deterministic Routing Planner',
                                                 'badges': ['Deterministic', 'Routing', 'Risk-Aware'],
                                                 'purpose': 'Calculates complexity and tells the Supervisor '
                                                            'which reasoning branches to run.',
                                                 'why_needed': 'Spot reasoning should run only when urgency '
                                                               'or infeasibility justifies it.',
                                                 'routing': 'The Supervisor requests a deterministic routing '
                                                            'recommendation before LLM reasoning.',
                                                 'reads_state': ['demand_analysis',
                                                                 'supplier_intelligence_output',
                                                                 'required_date'],
                                                 'reads_database': ['No direct database access.'],
                                                 'tools': [('Timeline pressure score', 'Measure urgency.'),
                                                           ('Supplier availability score',
                                                            'Evaluate viable supplier coverage.'),
                                                           ('MOQ and capacity score',
                                                            'Measure execution complexity.'),
                                                           ('Route selector',
                                                            'Return required execution nodes.')],
                                                 'processing': ['Score risk dimensions',
                                                                'Calculate complexity',
                                                                'Select route',
                                                                'Explain route'],
                                                 'writes_state': ['risk_complexity_plan',
                                                                  'selected_route',
                                                                  'execution_nodes'],
                                                 'returns_to': 'Supervisor Agent',
                                                 'next_routes': ['Contracted only',
                                                                 'Contracted + spot',
                                                                 'Risk review',
                                                                 'Manual review'],
                                                 'source': 'agents/risk_complexity_planner.py',
                                                 'example': {'selected_route': 'contracted_then_spot',
                                                             'complexity_score': 37.0}},
                                'parallel_executor': {'title': 'Parallel Strategy Executor',
                                                      'type': 'Execution Coordinator',
                                                      'badges': ['Parallel',
                                                                 'Conditional',
                                                                 'Context Propagation'],
                                                      'purpose': 'Runs only the selected reasoning branches '
                                                                 'and allows them to overlap.',
                                                      'why_needed': 'Parallel execution reduces latency and '
                                                                    'keeps strategy outputs isolated.',
                                                      'routing': 'The Supervisor delegates here after '
                                                                 'reading execution_nodes from the risk '
                                                                 'plan.',
                                                      'reads_state': ['supplier_intelligence_output',
                                                                      'risk_complexity_plan',
                                                                      'execution_nodes'],
                                                      'reads_database': ['No direct database access.'],
                                                      'tools': [('ThreadPoolExecutor',
                                                                 'Run selected branches concurrently.'),
                                                                ('copy_context()',
                                                                 'Propagate logging and trace context.'),
                                                                ('Branch result merger',
                                                                 'Store isolated branch outputs.')],
                                                      'processing': ['Read selected branches',
                                                                     'Launch branches',
                                                                     'Wait for completion',
                                                                     'Return outputs'],
                                                      'writes_state': ['contracted_reasoning',
                                                                       'spot_reasoning'],
                                                      'returns_to': 'Supervisor Agent',
                                                      'next_routes': ['Decision Aggregator',
                                                                      'Failure handling'],
                                                      'source': 'agents/supervisor.py',
                                                      'example': {'execution_mode': 'parallel',
                                                                  'strategies': ['contracted_reasoning',
                                                                                 'spot_reasoning']}},
                                'contracted_reasoning': {'title': 'Contracted Supplier Reasoning',
                                                         'type': 'LLM-Powered Item Reasoning',
                                                         'badges': ['LLM', 'Item-Level', 'Explainable'],
                                                         'purpose': 'Selects and explains the best '
                                                                    'contracted supplier per item.',
                                                         'why_needed': 'Selection requires trade-off '
                                                                       'reasoning across cost, schedule, '
                                                                       'capacity, quality, and risk.',
                                                         'routing': 'Invoked when the planner requires '
                                                                    'contracted evaluation.',
                                                         'reads_state': ['supplier_intelligence_output',
                                                                         'required_date',
                                                                         'demand_analysis'],
                                                         'reads_database': ['No direct access; consumes '
                                                                            'enriched supplier facts.'],
                                                         'tools': [('ChatOpenAI structured output',
                                                                    'Generate validated recommendations.'),
                                                                   ('Pydantic models',
                                                                    'Enforce recommendation and alternatives '
                                                                    'schema.'),
                                                                   ('Precomputed cost fields',
                                                                    'Provide MOQ, discount, total cost, and '
                                                                    'unit price.')],
                                                         'processing': ['Evaluate feasibility',
                                                                        'Compare commercial and risk factors',
                                                                        'Rank alternatives',
                                                                        'Explain choice'],
                                                         'writes_state': ['contracted_reasoning'],
                                                         'returns_to': 'Parallel Executor, then Supervisor',
                                                         'next_routes': ['Decision Aggregator'],
                                                         'source': 'agents/reasoning_node.py',
                                                         'example': {'item_id': 'BR-6205',
                                                                     'selected_supplier': 'NSK Americas'}},
                                'spot_reasoning': {'title': 'Spot Supplier Reasoning',
                                                   'type': 'LLM-Powered Item Reasoning',
                                                   'badges': ['LLM', 'Item-Level', 'Urgency-Aware'],
                                                   'purpose': 'Selects and explains the best spot supplier '
                                                              'per item.',
                                                   'why_needed': 'Urgent requirements may justify a cost '
                                                                 'premium to protect production timing.',
                                                   'routing': 'Invoked only when the planner identifies a '
                                                              'need for spot comparison.',
                                                   'reads_state': ['supplier_intelligence_output',
                                                                   'required_date',
                                                                   'demand_analysis'],
                                                   'reads_database': ['No direct access; consumes enriched '
                                                                      'spot facts.'],
                                                   'tools': [('ChatOpenAI structured output',
                                                              'Generate validated recommendations.'),
                                                             ('Item standard lead time',
                                                              'Ground schedule comparisons.'),
                                                             ('Precomputed spot pricing',
                                                              'Use spot cost without contracted discounts.')],
                                                   'processing': ['Evaluate feasibility',
                                                                  'Compare schedule recovery',
                                                                  'Evaluate premium and risk',
                                                                  'Explain trade-offs'],
                                                   'writes_state': ['spot_reasoning'],
                                                   'returns_to': 'Parallel Executor, then Supervisor',
                                                   'next_routes': ['Decision Aggregator'],
                                                   'source': 'agents/spot_reasoning_node.py',
                                                   'example': {'item_id': 'BR-6205',
                                                               'selected_supplier': 'Indiana Aluminum '
                                                                                    'Castings'}},
                                'decision_aggregator': {'title': 'Decision Aggregator',
                                                        'type': 'Deterministic Product-Level Decision',
                                                        'badges': ['Deterministic',
                                                                   'Explainable',
                                                                   'Product-Level'],
                                                        'purpose': 'Combines strategy results into one '
                                                                   'actionable procurement recommendation.',
                                                        'why_needed': 'Item recommendations must become a '
                                                                      'product-level strategy.',
                                                        'routing': 'The Supervisor routes here after all '
                                                                   'required reasoning branches finish.',
                                                        'reads_state': ['risk_complexity_plan',
                                                                        'contracted_reasoning',
                                                                        'spot_reasoning'],
                                                        'reads_database': ['No direct database access.'],
                                                        'tools': [('Feasibility comparison',
                                                                   'Compare schedule viability.'),
                                                                  ('Cost delta calculator',
                                                                   'Measure strategy premium or savings.'),
                                                                  ('Schedule recovery calculator',
                                                                   'Measure time benefit.'),
                                                                  ('Hybrid plan builder',
                                                                   'Use contracted items within the spot '
                                                                   'critical path.')],
                                                        'processing': ['Check feasibility',
                                                                       'Compare cost and critical path',
                                                                       'Select strategy',
                                                                       'Set confidence and review '
                                                                       'requirement'],
                                                        'writes_state': ['decision_aggregation'],
                                                        'returns_to': 'Supervisor Agent',
                                                        'next_routes': ['Human Decision Review',
                                                                        'Workflow Complete'],
                                                        'source': 'agents/decision_aggregator.py',
                                                        'example': {'recommended_strategy': 'spot_procurement',
                                                                    'decision_confidence': 'high'}},
                                'human_review': {'title': 'Human Decision Review',
                                                 'type': 'Human-in-the-Loop Control',
                                                 'badges': ['Human', 'Auditable', 'Persistent'],
                                                 'purpose': 'Allows acceptance or documented strategy and '
                                                            'supplier overrides.',
                                                 'why_needed': 'Enterprise procurement requires human '
                                                               'accountability and immutable AI evidence.',
                                                 'routing': 'Presented after the Supervisor completes the '
                                                            'procurement workflow.',
                                                 'reads_state': ['decision_aggregation',
                                                                 'contracted_reasoning',
                                                                 'spot_reasoning',
                                                                 'supplier_intelligence_output'],
                                                 'reads_database': ['Workflow run',
                                                                    'Saved review activity',
                                                                    'Decision overrides'],
                                                 'tools': [('build_effective_procurement_plan()',
                                                            'Preserve AI output and apply valid human '
                                                            'changes.'),
                                                           ('Supplier override validation',
                                                            'Rebuild overridden lines from supplier '
                                                            'intelligence.'),
                                                           ('Review persistence',
                                                            'Store changes, reason, reviewer, and effective '
                                                            'plan.')],
                                                 'processing': ['Preserve AI recommendation',
                                                                'Apply strategy override',
                                                                'Apply supplier overrides',
                                                                'Recalculate metrics',
                                                                'Persist review'],
                                                 'writes_state': ['effective_decision',
                                                                  'human_decision',
                                                                  'effective_plan',
                                                                  'effective_metrics'],
                                                 'returns_to': 'Application UI',
                                                 'next_routes': ['Create Purchase Requisition',
                                                                 'Continue review'],
                                                 'source': 'decision_review.py / ui/review.py',
                                                 'example': {'approval_status': 'override_applied',
                                                             'supplier_overrides': {'BR-6205': 'Bosch '
                                                                                               'Rexroth '
                                                                                               'USA'}}}}},
 'conversation': {'title': 'Conversation Workflow',
                  'description': 'Stateful procurement Q&A with entity resolution, selective context, '
                                 'grounded answers, and persistent memory.',
                  'entry': 'conversation_service',
                  'components': {'conversation_service': {'title': 'Conversation Service',
                                                          'type': 'Conversation Orchestrator',
                                                          'badges': ['Conversation', 'Conversation'],
                                                          'purpose': 'Coordinates loading memory, query '
                                                                     'analysis, context building, answer '
                                                                     'generation, persistence, and '
                                                                     'summarization.',
                                                          'why_needed': 'Coordinates loading memory, query '
                                                                        'analysis, context building, answer '
                                                                        'generation, persistence, and '
                                                                        'summarization.',
                                                          'routing': 'Coordinated by the Conversation '
                                                                     'Service.',
                                                          'reads_state': ['session_id',
                                                                          'latest workflow',
                                                                          'messages',
                                                                          'summary'],
                                                          'reads_database': ['app_workflow_runs',
                                                                             'app_conversation_messages',
                                                                             'app_conversation_summaries'],
                                                          'tools': [('Conversation coordinator',
                                                                     'Conversation coordinator'),
                                                                    ('Persistence APIs', 'Persistence APIs')],
                                                          'processing': ['Coordinates loading memory, query '
                                                                         'analysis, context building, answer '
                                                                         'generation, persistence, and '
                                                                         'summarization.'],
                                                          'writes_state': ['query_analysis',
                                                                           'selected_context',
                                                                           'assistant_answer'],
                                                          'returns_to': 'Conversation Service',
                                                          'next_routes': ['Next conversation stage'],
                                                          'source': 'conversation/service.py',
                                                          'example': {'component': 'conversation_service',
                                                                      'status': 'success'}},
                                 'entity_index': {'title': 'Entity Index',
                                                  'type': 'Deterministic Retrieval Index',
                                                  'badges': ['Deterministic', 'Conversation'],
                                                  'purpose': 'Indexes products, items, suppliers, '
                                                             'strategies, and recommendations for follow-up '
                                                             'references.',
                                                  'why_needed': 'Indexes products, items, suppliers, '
                                                                'strategies, and recommendations for '
                                                                'follow-up references.',
                                                  'routing': 'Coordinated by the Conversation Service.',
                                                  'reads_state': ['latest workflow',
                                                                  'persisted entity index'],
                                                  'reads_database': ['app_workflow_runs.entity_index_json'],
                                                  'tools': [('Entity extraction', 'Entity extraction'),
                                                            ('Entity resolution', 'Entity resolution')],
                                                  'processing': ['Indexes products, items, suppliers, '
                                                                 'strategies, and recommendations for '
                                                                 'follow-up references.'],
                                                  'writes_state': ['entity_index', 'resolved_entities'],
                                                  'returns_to': 'Conversation Service',
                                                  'next_routes': ['Next conversation stage'],
                                                  'source': 'conversation/entity_index.py',
                                                  'example': {'component': 'entity_index',
                                                              'status': 'success'}},
                                 'query_analyzer': {'title': 'Query Analyzer',
                                                    'type': 'LLM Structured Analysis',
                                                    'badges': ['LLM', 'Conversation'],
                                                    'purpose': 'Classifies intent and determines the minimum '
                                                               'context scope needed.',
                                                    'why_needed': 'Classifies intent and determines the '
                                                                  'minimum context scope needed.',
                                                    'routing': 'Coordinated by the Conversation Service.',
                                                    'reads_state': ['question',
                                                                    'resolved entities',
                                                                    'summary',
                                                                    'messages'],
                                                    'reads_database': [],
                                                    'tools': [('ChatOpenAI structured output',
                                                               'ChatOpenAI structured output'),
                                                              ('Pydantic query model',
                                                               'Pydantic query model')],
                                                    'processing': ['Classifies intent and determines the '
                                                                   'minimum context scope needed.'],
                                                    'writes_state': ['query_analysis'],
                                                    'returns_to': 'Conversation Service',
                                                    'next_routes': ['Next conversation stage'],
                                                    'source': 'conversation/query_analyzer.py',
                                                    'example': {'component': 'query_analyzer',
                                                                'status': 'success'}},
                                 'context_builder': {'title': 'Selective Context Builder',
                                                     'type': 'Deterministic Context Assembly',
                                                     'badges': ['Deterministic', 'Conversation'],
                                                     'purpose': 'Builds only the workflow context required '
                                                                'by the analyzed question.',
                                                     'why_needed': 'Builds only the workflow context '
                                                                   'required by the analyzed question.',
                                                     'routing': 'Coordinated by the Conversation Service.',
                                                     'reads_state': ['query_analysis',
                                                                     'workflow run',
                                                                     'entity index',
                                                                     'memory'],
                                                     'reads_database': ['Workflow and conversation '
                                                                        'persistence'],
                                                     'tools': [('Context selectors', 'Context selectors'),
                                                               ('Entity filters', 'Entity filters')],
                                                     'processing': ['Builds only the workflow context '
                                                                    'required by the analyzed question.'],
                                                     'writes_state': ['selected_context', 'context_metadata'],
                                                     'returns_to': 'Conversation Service',
                                                     'next_routes': ['Next conversation stage'],
                                                     'source': 'conversation/context_builder.py',
                                                     'example': {'component': 'context_builder',
                                                                 'status': 'success'}},
                                 'answer_generator': {'title': 'Answer Generator',
                                                      'type': 'LLM Grounded Generation',
                                                      'badges': ['LLM', 'Conversation'],
                                                      'purpose': 'Generates grounded procurement answers '
                                                                 'from selective context.',
                                                      'why_needed': 'Generates grounded procurement answers '
                                                                    'from selective context.',
                                                      'routing': 'Coordinated by the Conversation Service.',
                                                      'reads_state': ['question',
                                                                      'query_analysis',
                                                                      'selected_context',
                                                                      'memory'],
                                                      'reads_database': [],
                                                      'tools': [('ChatOpenAI', 'ChatOpenAI'),
                                                                ('Answer guardrails', 'Answer guardrails')],
                                                      'processing': ['Generates grounded procurement answers '
                                                                     'from selective context.'],
                                                      'writes_state': ['assistant_answer', 'answer_metadata'],
                                                      'returns_to': 'Conversation Service',
                                                      'next_routes': ['Next conversation stage'],
                                                      'source': 'conversation/answer_generator.py',
                                                      'example': {'component': 'answer_generator',
                                                                  'status': 'success'}},
                                 'summarizer': {'title': 'Conversation Summarizer',
                                                'type': 'LLM Memory Compression',
                                                'badges': ['LLM', 'Conversation'],
                                                'purpose': 'Compresses older conversation into persistent '
                                                           'memory when required.',
                                                'why_needed': 'Compresses older conversation into persistent '
                                                              'memory when required.',
                                                'routing': 'Coordinated by the Conversation Service.',
                                                'reads_state': ['recent messages', 'previous summary'],
                                                'reads_database': ['app_conversation_messages',
                                                                   'app_conversation_summaries'],
                                                'tools': [('Summarization model', 'Summarization model'),
                                                          ('Summary persistence', 'Summary persistence')],
                                                'processing': ['Compresses older conversation into '
                                                               'persistent memory when required.'],
                                                'writes_state': ['conversation_summary', 'messages_covered'],
                                                'returns_to': 'Conversation Service',
                                                'next_routes': ['Next conversation stage'],
                                                'source': 'conversation/summarizer.py',
                                                'example': {'component': 'summarizer',
                                                            'status': 'success'}}}},
 'pr_po': {'title': 'PR → PO Workflow',
           'description': 'Deterministic execution from reviewed recommendation through approval and '
                          'supplier-specific purchase orders.',
           'entry': 'purchase_requisition',
           'components': {'purchase_requisition': {'title': 'Purchase Requisition',
                                                   'type': 'Deterministic Business Document',
                                                   'badges': ['Deterministic', 'PR → PO'],
                                                   'purpose': 'Builds and persists a PR from the reviewed '
                                                              'effective decision.',
                                                   'why_needed': 'Builds and persists a PR from the reviewed '
                                                                 'effective decision.',
                                                   'routing': 'Controlled by PR status and deterministic '
                                                              'execution rules.',
                                                   'reads_state': ['effective_decision',
                                                                   'effective_plan',
                                                                   'session_id',
                                                                   'run_id'],
                                                   'reads_database': ['PR tables',
                                                                      'Saved review',
                                                                      'Requester identity'],
                                                   'tools': [('PR preview builder', 'PR preview builder'),
                                                             ('PR creation service', 'PR creation service'),
                                                             ('Decision source comparison',
                                                              'Decision source comparison')],
                                                   'processing': ['Builds and persists a PR from the '
                                                                  'reviewed effective decision.'],
                                                   'writes_state': ['pr_id',
                                                                    'pr_status',
                                                                    'pr_lines',
                                                                    'pr_total'],
                                                   'returns_to': 'PR UI / Execution Orchestrator',
                                                   'next_routes': ['Next legal PR → PO action'],
                                                   'source': 'pr_po/purchase_requisition.py',
                                                   'example': {'component': 'purchase_requisition',
                                                               'status': 'success'}},
                          'approval_service': {'title': 'Approval Service',
                                               'type': 'Deterministic Authorization',
                                               'badges': ['Deterministic', 'PR → PO'],
                                               'purpose': 'Validates approver identity, role, code, '
                                                          'separation of duties, and approval limit.',
                                               'why_needed': 'Validates approver identity, role, code, '
                                                             'separation of duties, and approval limit.',
                                               'routing': 'Controlled by PR status and deterministic '
                                                          'execution rules.',
                                               'reads_state': ['pr_id',
                                                               'pr_status',
                                                               'pr_total',
                                                               'requester_user_id'],
                                               'reads_database': ['PR data', 'Approvers', 'Approval history'],
                                               'tools': [('Eligible approver lookup',
                                                          'Eligible approver lookup'),
                                                         ('Credential validation', 'Credential validation'),
                                                         ('Status transition', 'Status transition')],
                                               'processing': ['Validates approver identity, role, code, '
                                                              'separation of duties, and approval limit.'],
                                               'writes_state': ['approval_status', 'approved_by'],
                                               'returns_to': 'PR UI / Execution Orchestrator',
                                               'next_routes': ['Next legal PR → PO action'],
                                               'source': 'pr_po/approval_service.py',
                                               'example': {'component': 'approval_service',
                                                           'status': 'success'}},
                          'execution_supervisor': {'title': 'PR-to-PO Execution Supervisor',
                                                   'type': 'Deterministic State Machine',
                                                   'badges': ['Deterministic', 'PR → PO'],
                                                   'purpose': 'Selects the next legal action from PR status '
                                                              'and existing PO state.',
                                                   'why_needed': 'Selects the next legal action from PR '
                                                                 'status and existing PO state.',
                                                   'routing': 'Controlled by PR status and deterministic '
                                                              'execution rules.',
                                                   'reads_state': ['pr_id', 'status', 'has_purchase_orders'],
                                                   'reads_database': ['PR status', 'Existing POs'],
                                                   'tools': [('determine_next_action()',
                                                              'determine_next_action()'),
                                                             ('Duplicate PO protection',
                                                              'Duplicate PO protection')],
                                                   'processing': ['Selects the next legal action from PR '
                                                                  'status and existing PO state.'],
                                                   'writes_state': ['next_action', 'can_execute', 'reason'],
                                                   'returns_to': 'PR UI / Execution Orchestrator',
                                                   'next_routes': ['Next legal PR → PO action'],
                                                   'source': 'pr_po/execution_supervisor.py',
                                                   'example': {'component': 'execution_supervisor',
                                                               'status': 'success'}},
                          'po_generation': {'title': 'Purchase Order Generation',
                                            'type': 'Deterministic Execution Service',
                                            'badges': ['Deterministic', 'PR → PO'],
                                            'purpose': 'Creates supplier-specific POs and reconciles their '
                                                       'total to the PR.',
                                            'why_needed': 'Creates supplier-specific POs and reconciles '
                                                          'their total to the PR.',
                                            'routing': 'Controlled by PR status and deterministic execution '
                                                       'rules.',
                                            'reads_state': ['approved PR',
                                                            'PR lines',
                                                            'supplier assignments'],
                                            'reads_database': ['PR and PO tables'],
                                            'tools': [('Supplier grouping', 'Supplier grouping'),
                                                      ('PO ID generator', 'PO ID generator'),
                                                      ('Financial reconciliation',
                                                       'Financial reconciliation'),
                                                      ('Status transition', 'Status transition')],
                                            'processing': ['Creates supplier-specific POs and reconciles '
                                                           'their total to the PR.'],
                                            'writes_state': ['purchase_orders',
                                                             'reconciliation',
                                                             'final_status'],
                                            'returns_to': 'PR UI / Execution Orchestrator',
                                            'next_routes': ['Next legal PR → PO action'],
                                            'source': 'pr_po/po_generation.py',
                                            'example': {'component': 'po_generation', 'status': 'success'}}}},
 'services': {'title': 'Shared Platform Services',
              'description': 'Cross-cutting persistence, observability, configuration, and error-handling '
                             'services.',
              'entry': 'persistence',
              'components': {'persistence': {'title': 'Persistence',
                                             'type': 'Shared Platform Service',
                                             'badges': ['Shared', 'Platform'],
                                             'purpose': 'Stores users, sessions, workflow runs, messages, '
                                                        'summaries, reviews, and activity.',
                                             'why_needed': 'Stores users, sessions, workflow runs, messages, '
                                                           'summaries, reviews, and activity.',
                                             'routing': 'Used by all workflows as a shared dependency.',
                                             'reads_state': ['Application records'],
                                             'reads_database': ['Application-prefixed SQLite tables'],
                                             'tools': [('SQLite transactions', 'SQLite transactions'),
                                                       ('Guarded schema initialization',
                                                        'Guarded schema initialization'),
                                                       ('JSON serialization', 'JSON serialization')],
                                             'processing': ['Stores users, sessions, workflow runs, '
                                                            'messages, summaries, reviews, and activity.'],
                                             'writes_state': ['Persisted and restored state'],
                                             'returns_to': 'Calling workflow',
                                             'next_routes': ['Return service result'],
                                             'source': 'persistence.py',
                                             'example': {'component': 'persistence', 'status': 'ready'}},
                             'observability': {'title': 'LangSmith and Structured Logging',
                                               'type': 'Shared Platform Service',
                                               'badges': ['Shared', 'Platform'],
                                               'purpose': 'Provides nested tracing, JSON events, durations, '
                                                          'failures, and audit visibility.',
                                               'why_needed': 'Provides nested tracing, JSON events, '
                                                             'durations, failures, and audit visibility.',
                                               'routing': 'Used by all workflows as a shared dependency.',
                                               'reads_state': ['Trace metadata', 'Event context'],
                                               'reads_database': [],
                                               'tools': [('LangSmith tracing', 'LangSmith tracing'),
                                                         ('Structured JSON logger', 'Structured JSON logger'),
                                                         ('Sensitive-field redaction',
                                                          'Sensitive-field redaction')],
                                               'processing': ['Provides nested tracing, JSON events, '
                                                              'durations, failures, and audit visibility.'],
                                               'writes_state': ['Trace records', 'JSONL logs'],
                                               'returns_to': 'Calling workflow',
                                               'next_routes': ['Return service result'],
                                               'source': 'core/observability.py / core/logging.py',
                                               'example': {'component': 'observability', 'status': 'ready'}},
                             'configuration': {'title': 'Configuration and Error Handling',
                                               'type': 'Shared Platform Service',
                                               'badges': ['Shared', 'Platform'],
                                               'purpose': 'Centralizes environment settings, model '
                                                          'configuration, database paths, and controlled '
                                                          'exceptions.',
                                               'why_needed': 'Centralizes environment settings, model '
                                                             'configuration, database paths, and controlled '
                                                             'exceptions.',
                                               'routing': 'Used by all workflows as a shared dependency.',
                                               'reads_state': ['Environment variables'],
                                               'reads_database': [],
                                               'tools': [('Settings dataclass', 'Settings dataclass'),
                                                         ('.env loading', '.env loading'),
                                                         ('Custom exceptions', 'Custom exceptions')],
                                               'processing': ['Centralizes environment settings, model '
                                                              'configuration, database paths, and controlled '
                                                              'exceptions.'],
                                               'writes_state': ['Application configuration'],
                                               'returns_to': 'Calling workflow',
                                               'next_routes': ['Return service result'],
                                               'source': 'core/config.py / core/exceptions.py',
                                               'example': {'component': 'configuration',
                                                           'status': 'ready'}}}}}

WORKFLOW_ORDER = ['procurement', 'conversation', 'pr_po', 'services']
