"""
decision_aggregator_v1.py
Version: 1.0-deterministic-strategy-aggregation

Deterministic Decision Aggregator for the Multi-Agent Procurement System.

Purpose:
- Compare contracted and spot procurement strategy outputs already generated by
  the reasoning nodes.
- Do NOT call an LLM.
- Do NOT recalculate supplier decisions.
- Assemble a business-facing recommended procurement strategy with both an
  executive summary and detailed item-level procurement plan.

Design note:
This is intentionally named Decision Aggregator, not Final Decision, because
human-in-the-loop approval is planned for a later phase.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple
from datetime import datetime

AGGREGATOR_VERSION = "decision_aggregator_v2 | 1.1-planner-context-and-buffer-aware"


# ============================================================
# Helpers
# ============================================================

def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None or value == "N/A":
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        if value is None or value == "N/A":
            return default
        return int(float(value))
    except (TypeError, ValueError):
        return default


def _round_money(value: Any) -> float:
    return round(_safe_float(value), 2)


def _get_product_level(strategy_result: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    if not strategy_result:
        return {}
    return strategy_result.get("product_level") or {}


def _get_items(strategy_result: Optional[Dict[str, Any]]) -> List[Dict[str, Any]]:
    if not strategy_result:
        return []
    return strategy_result.get("items") or []


def _index_demand_items(demand_analysis: Optional[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    indexed: Dict[str, Dict[str, Any]] = {}
    if not demand_analysis:
        return indexed
    for item in demand_analysis.get("item_analysis", []) or []:
        item_id = item.get("item_id")
        if item_id:
            indexed[item_id] = item
    return indexed


def _build_strategy_summary(name: str, result: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    product_level = _get_product_level(result)
    exists = bool(product_level)

    return {
        "strategy": name,
        "available": exists,
        "critical_path_days": _safe_int(product_level.get("critical_path_days"), 0) if exists else None,
        "suggested_realistic_date": product_level.get("suggested_realistic_date") if exists else None,
        "is_original_date_feasible": bool(product_level.get("is_original_date_feasible", False)) if exists else False,
        "total_procurement_cost": _round_money(product_level.get("total_procurement_cost")) if exists else None,
        "overall_message": product_level.get("overall_message") if exists else None,
        "buffer_days": product_level.get("buffer_days") if exists else None,
        "days_required_with_buffer": product_level.get("days_required_with_buffer") if exists else None,
        "chosen_suppliers_summary": product_level.get("chosen_suppliers_summary", []) if exists else [],
    }


def _extract_reasoning_item_by_id(strategy_result: Optional[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    indexed: Dict[str, Dict[str, Any]] = {}
    for item in _get_items(strategy_result):
        item_id = item.get("item_id")
        if item_id:
            indexed[item_id] = item
    return indexed


def _item_procurement_plan(
    selected_strategy: str,
    selected_result: Optional[Dict[str, Any]],
    demand_analysis: Optional[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Build item-level plan from selected strategy reasoning output."""
    demand_index = _index_demand_items(demand_analysis)
    plan: List[Dict[str, Any]] = []

    for item in _get_items(selected_result):
        rec = item.get("recommended_supplier") or {}
        item_id = item.get("item_id")
        demand_item = demand_index.get(item_id, {})
        inv = demand_item.get("inventory_status") or {}

        # Use selected node's explicit order quantity if available, otherwise infer.
        order_quantity = rec.get("recommended_order_quantity")
        if order_quantity is None:
            order_quantity = _safe_float(item.get("gross_requirement")) + _safe_float(rec.get("overage_quantity"))

        alternatives = []
        for alt in item.get("alternatives_considered", []) or []:
            alternatives.append({
                "supplier_name": alt.get("supplier_name"),
                "why_not_selected": alt.get("why_not_selected"),
                "total_cost": alt.get("total_cost"),
                "spot_total_cost": alt.get("total_spot_cost"),
                "risk_level": alt.get("risk_level"),
                "item_standard_lead_time_days": alt.get("item_standard_lead_time_days"),
            })

        plan.append({
            "item_id": item_id,
            "item_name": item.get("item_name"),
            "strategy": selected_strategy,
            "gross_requirement": item.get("gross_requirement"),
            "net_requirement": demand_item.get("net_requirement"),
            "current_stock": inv.get("current_stock"),
            "reserved_qty": inv.get("reserved_qty"),
            "on_order_qty": inv.get("on_order_qty"),
            "safety_stock": inv.get("safety_stock"),
            "selected_supplier_id": rec.get("supplier_id"),
            "selected_supplier_name": rec.get("supplier_name"),
            "order_quantity": order_quantity,
            "lead_time_days": rec.get("lead_time_days"),
            "can_deliver_on_time": rec.get("can_deliver_on_time"),
            "risk_level": rec.get("risk_level"),
            "total_cost": rec.get("total_cost"),
            "effective_unit_price": rec.get("effective_unit_price"),
            "overage_quantity": rec.get("overage_quantity"),
            "bulk_discount_applied": rec.get("bulk_discount_applied"),
            "reasoning": rec.get("reasoning"),
            "key_tradeoffs": item.get("key_tradeoffs", []),
            "overall_assessment": item.get("overall_assessment"),
            "alternatives_considered": alternatives,
        })

    return plan


def _decision_reason(
    recommended_strategy: str,
    contracted: Dict[str, Any],
    spot: Dict[str, Any],
    route: str,
    cost_delta: Optional[float],
    schedule_recovery_days: Optional[int],
) -> str:
    c_available = contracted.get("available")
    s_available = spot.get("available")
    c_feasible = contracted.get("is_original_date_feasible", False)
    s_feasible = spot.get("is_original_date_feasible", False)

    if recommended_strategy == "contracted_procurement" and c_available and not s_available:
        return "Contracted procurement is recommended because the planner determined spot reasoning was not needed for this request."

    if recommended_strategy == "spot_procurement" and c_available and s_available and not c_feasible and s_feasible:
        return (
            f"Spot procurement is recommended because the contracted path misses the required date, "
            f"while spot procurement meets it. The additional cost is {cost_delta}, "
            f"and the estimated schedule recovery is {schedule_recovery_days} day(s)."
        )

    if recommended_strategy == "contracted_procurement" and c_available and s_available and c_feasible:
        return (
            "Contracted procurement is recommended because it can meet the required date. "
            "Spot procurement does not provide enough business value to justify the additional comparison cost/premium."
        )

    if recommended_strategy == "spot_procurement" and s_available and not c_available:
        return "Spot procurement is recommended because spot is the only available evaluated strategy."

    if recommended_strategy == "human_review_required":
        return (
            "Human review is recommended because neither evaluated strategy clearly satisfies the business objective "
            "or the risk/cost/timeline trade-off requires approval."
        )

    return f"Recommendation was selected using deterministic strategy comparison rules for route '{route}'."


# ============================================================
# Main Aggregator
# ============================================================

def aggregate_procurement_decision(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Aggregate prior node outputs into a deterministic procurement decision.

    Expected state keys:
    - demand_analysis
    - supplier_intelligence_output
    - risk_complexity_plan
    - contracted_reasoning
    - spot_reasoning (optional)
    """
    demand_analysis = state.get("demand_analysis") or {}
    supplier_output = state.get("supplier_intelligence_output") or {}
    planner = (
        state.get("risk_complexity_plan")
        or state.get("procurement_complexity_plan")
        or state.get("route_plan")
        or {}
    )
    contracted_result = state.get("contracted_reasoning")
    spot_result = state.get("spot_reasoning")

    contracted = _build_strategy_summary("contracted", contracted_result)
    spot = _build_strategy_summary("spot", spot_result)

    c_available = contracted["available"]
    s_available = spot["available"]
    c_feasible = contracted["is_original_date_feasible"]
    s_feasible = spot["is_original_date_feasible"]
    c_cost = contracted["total_procurement_cost"]
    s_cost = spot["total_procurement_cost"]
    c_days = contracted["critical_path_days"]
    s_days = spot["critical_path_days"]

    cost_delta: Optional[float] = None
    cost_delta_pct: Optional[float] = None
    schedule_recovery_days: Optional[int] = None

    if c_available and s_available and c_cost is not None and s_cost is not None:
        cost_delta = round(s_cost - c_cost, 2)
        cost_delta_pct = round((cost_delta / c_cost) * 100, 2) if c_cost else None

    if c_available and s_available and c_days is not None and s_days is not None:
        schedule_recovery_days = int(c_days - s_days)

    route = planner.get("selected_route") or "unknown"
    complexity_score = planner.get("complexity_score")
    complexity_level = planner.get("complexity_level")

    # ------------------------------
    # Deterministic strategy rules
    # ------------------------------
    recommended_strategy = "human_review_required"
    human_review_required = False
    decision_confidence = "medium"

    if c_available and not s_available:
        recommended_strategy = "contracted_procurement"
        human_review_required = "risk_review" in route
        decision_confidence = "high" if c_feasible else "medium"

    elif s_available and not c_available:
        recommended_strategy = "spot_procurement"
        human_review_required = True
        decision_confidence = "medium"

    elif c_available and s_available:
        if not c_feasible and s_feasible:
            recommended_strategy = "spot_procurement"
            human_review_required = True
            decision_confidence = "high"
        elif c_feasible and not s_feasible:
            recommended_strategy = "contracted_procurement"
            human_review_required = "risk_review" in route
            decision_confidence = "high"
        elif c_feasible and s_feasible:
            # If both can meet date, prefer contracted unless spot is cheaper or materially useful.
            if cost_delta is not None and cost_delta < 0:
                recommended_strategy = "spot_procurement"
                human_review_required = True
                decision_confidence = "medium"
            else:
                recommended_strategy = "contracted_procurement"
                human_review_required = "risk_review" in route
                decision_confidence = "high"
        else:
            # Neither meets date: choose the one with better critical path, but require review.
            if s_days is not None and c_days is not None and s_days < c_days:
                recommended_strategy = "spot_procurement"
            else:
                recommended_strategy = "contracted_procurement"
            human_review_required = True
            decision_confidence = "low"

    selected_result = contracted_result if recommended_strategy == "contracted_procurement" else spot_result
    selected_strategy_label = "contracted" if recommended_strategy == "contracted_procurement" else "spot"

    procurement_plan = _item_procurement_plan(
        selected_strategy=selected_strategy_label,
        selected_result=selected_result,
        demand_analysis=demand_analysis,
    )

    product_id = supplier_output.get("product_id") or demand_analysis.get("product_id") or state.get("product_id")
    required_date = supplier_output.get("required_date") or demand_analysis.get("required_date") or state.get("current_date")

    decision_summary = _decision_reason(
        recommended_strategy=recommended_strategy,
        contracted=contracted,
        spot=spot,
        route=route,
        cost_delta=cost_delta,
        schedule_recovery_days=schedule_recovery_days,
    )

    item_count = len(procurement_plan)
    selected_total_cost = None
    selected_critical_path_days = None
    selected_realistic_date = None
    selected_feasible = False

    if recommended_strategy == "contracted_procurement":
        selected_total_cost = c_cost
        selected_critical_path_days = c_days
        selected_realistic_date = contracted.get("suggested_realistic_date")
        selected_feasible = c_feasible
    elif recommended_strategy == "spot_procurement":
        selected_total_cost = s_cost
        selected_critical_path_days = s_days
        selected_realistic_date = spot.get("suggested_realistic_date")
        selected_feasible = s_feasible

    return {
        "aggregator_version": AGGREGATOR_VERSION,
        "generated_at": datetime.now().isoformat(),
        "product_id": product_id,
        "required_date": required_date,
        "recommended_strategy": recommended_strategy,
        "selected_strategy_label": selected_strategy_label,
        "decision_confidence": decision_confidence,
        "human_review_required": human_review_required,
        "decision_summary": decision_summary,
        "selected_strategy_metrics": {
            "is_original_date_feasible": selected_feasible,
            "critical_path_days": selected_critical_path_days,
            "suggested_realistic_date": selected_realistic_date,
            "total_procurement_cost": selected_total_cost,
            "items_in_plan": item_count,
        },
        "strategy_comparison": {
            "contracted": contracted,
            "spot": spot,
            "cost_delta_spot_minus_contracted": cost_delta,
            "cost_delta_pct_spot_vs_contracted": cost_delta_pct,
            "schedule_recovery_days_from_spot": schedule_recovery_days,
        },
        "planner_context": {
            "selected_route": route,
            "complexity_score": complexity_score,
            "complexity_level": complexity_level,
            "route_reason": planner.get("route_reason"),
            "routing_flags": planner.get("routing_flags", {}),
            "top_signals": planner.get("top_signals", []),
        },
        "procurement_plan": procurement_plan,
    }
